/* eslint-disable guard-for-in */
/* eslint-disable no-underscore-dangle */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function SolidModel({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/shaji_7.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]} scale={0.1}>
        <group position={[0, 6.15, 0]} scale={[0.1, 0.1, 0.1]}>
          <mesh
            geometry={nodes.Mesh150.geometry}
            material={materials.Color_000}
          />
          <mesh
            geometry={nodes.Mesh150_1.geometry}
            material={materials.Color_F08}
          />
          <mesh
            geometry={nodes.Mesh150_2.geometry}
            material={materials.Color_B24}
          />
          <mesh
            geometry={nodes.Mesh150_3.geometry}
            material={materials._Color_A02_2}
          />
          <mesh
            geometry={nodes.Mesh150_4.geometry}
            material={materials.Color_F24}
          />
          <mesh
            geometry={nodes.Mesh150_5.geometry}
            material={materials.Color_A06}
          />
          <mesh
            geometry={nodes.Mesh150_6.geometry}
            material={materials.Translucent_Glass_Tinted}
          />
          <mesh
            geometry={nodes.Mesh150_7.geometry}
            material={materials._Metal_Rusted_1}
          />
          <mesh
            geometry={nodes.Mesh150_8.geometry}
            material={materials.Color_A02}
          />
          <mesh
            geometry={nodes.Mesh150_9.geometry}
            material={materials._Color_A02_1}
          />
          <mesh
            geometry={nodes.Mesh150_10.geometry}
            material={materials.Roofing_Shingles_Multi}
          />
          <mesh
            geometry={nodes.Mesh150_11.geometry}
            material={materials.Roofing_Slate_Dark}
          />
          <mesh
            geometry={nodes.Mesh150_12.geometry}
            material={materials.Translucent_Glass_Gray}
          />
          <mesh
            geometry={nodes.Mesh150_13.geometry}
            material={materials.Color_008}
          />
          <mesh
            geometry={nodes.Mesh150_14.geometry}
            material={materials.Color_A18}
          />
          <points
            geometry={nodes.Mesh150_15.geometry}
            material={materials.Color_000}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/shaji_7.glb");
